//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamsaz.PersonnlsApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jamsaz.PersonnlsApplication.Resources.EnumNames", typeof(EnumNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبول در حال انتظار.
        /// </summary>
        internal static string AcceptedWaiting {
            get {
                return ResourceManager.GetString("AcceptedWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان قراردادجاری.
        /// </summary>
        internal static string CurrentContractEndDate {
            get {
                return ResourceManager.GetString("CurrentContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع قرارداد جاری.
        /// </summary>
        internal static string CurrentContractStartDate {
            get {
                return ResourceManager.GetString("CurrentContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اولین قرارداد.
        /// </summary>
        internal static string FirstContractStartDate {
            get {
                return ResourceManager.GetString("FirstContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر ستادی.
        /// </summary>
        internal static string GheireSetadi {
            get {
                return ResourceManager.GetString("GheireSetadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر ستادی فنی.
        /// </summary>
        internal static string GheireSetadiFanni {
            get {
                return ResourceManager.GetString("GheireSetadiFanni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال انتظار.
        /// </summary>
        internal static string InWaiting {
            get {
                return ResourceManager.GetString("InWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاهل.
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد صلاحیت.
        /// </summary>
        internal static string Rejcted {
            get {
                return ResourceManager.GetString("Rejcted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستادی اداری.
        /// </summary>
        internal static string SetadiEdari {
            get {
                return ResourceManager.GetString("SetadiEdari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستادی فنی.
        /// </summary>
        internal static string SetadiFanni {
            get {
                return ResourceManager.GetString("SetadiFanni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجرد.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
    }
}
