#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamsaz.PersonnlsApplication.BusinessObjects.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PwKara")]
	public partial class PwKaraDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PwKaraDataContext() : 
				base(global::Jamsaz.PersonnlsApplication.BusinessObjects.Properties.Settings.Default.PwKaraConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PwKaraDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PwKaraDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PwKaraDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PwKaraDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTaradodInWeek")]
		public ISingleResult<GetTaradodInWeekResult> GetTaradodInWeek([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDate", DbType="NVarChar(20)")] string sDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonnelsNumbers", DbType="NVarChar(2048)")] string personnelsNumbers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sDate, personnelsNumbers);
			return ((ISingleResult<GetTaradodInWeekResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTotalDaysForTaradodInWeek")]
		public ISingleResult<GetTotalDaysForTaradodInWeekResult> GetTotalDaysForTaradodInWeek([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDate", DbType="NVarChar(20)")] string sDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonnelsNumbers", DbType="NVarChar(2048)")] string personnelsNumbers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sDate, personnelsNumbers);
			return ((ISingleResult<GetTotalDaysForTaradodInWeekResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetTaradodInWeekResult
	{
		
		private System.Nullable<double> _Emp_no;
		
		private System.Nullable<int> _Saturday;
		
		private System.Nullable<int> _Sunday;
		
		private System.Nullable<int> _Monday;
		
		private System.Nullable<int> _TuseDay;
		
		private System.Nullable<int> _WendsDay;
		
		private System.Nullable<int> _Tuersday;
		
		private System.Nullable<int> _Friday;
		
		private System.Nullable<int> _TOTAL;
		
		public GetTaradodInWeekResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_no", DbType="Float")]
		public System.Nullable<double> Emp_no
		{
			get
			{
				return this._Emp_no;
			}
			set
			{
				if ((this._Emp_no != value))
				{
					this._Emp_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saturday", DbType="Int")]
		public System.Nullable<int> Saturday
		{
			get
			{
				return this._Saturday;
			}
			set
			{
				if ((this._Saturday != value))
				{
					this._Saturday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sunday", DbType="Int")]
		public System.Nullable<int> Sunday
		{
			get
			{
				return this._Sunday;
			}
			set
			{
				if ((this._Sunday != value))
				{
					this._Sunday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monday", DbType="Int")]
		public System.Nullable<int> Monday
		{
			get
			{
				return this._Monday;
			}
			set
			{
				if ((this._Monday != value))
				{
					this._Monday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuseDay", DbType="Int")]
		public System.Nullable<int> TuseDay
		{
			get
			{
				return this._TuseDay;
			}
			set
			{
				if ((this._TuseDay != value))
				{
					this._TuseDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WendsDay", DbType="Int")]
		public System.Nullable<int> WendsDay
		{
			get
			{
				return this._WendsDay;
			}
			set
			{
				if ((this._WendsDay != value))
				{
					this._WendsDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuersday", DbType="Int")]
		public System.Nullable<int> Tuersday
		{
			get
			{
				return this._Tuersday;
			}
			set
			{
				if ((this._Tuersday != value))
				{
					this._Tuersday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friday", DbType="Int")]
		public System.Nullable<int> Friday
		{
			get
			{
				return this._Friday;
			}
			set
			{
				if ((this._Friday != value))
				{
					this._Friday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Int")]
		public System.Nullable<int> TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
	}
	
	public partial class GetTotalDaysForTaradodInWeekResult
	{
		
		private System.Nullable<int> _TotalDays;
		
		public GetTotalDaysForTaradodInWeekResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDays", DbType="Int")]
		public System.Nullable<int> TotalDays
		{
			get
			{
				return this._TotalDays;
			}
			set
			{
				if ((this._TotalDays != value))
				{
					this._TotalDays = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
